#数据库主机地址
LoginCheckDB.DBHost = 127.0.0.1

#数据库名称
LoginCheckDB.DBName = gom_login_check

#数据库用户名
LoginCheckDB.DBUser = wcggame

#数据库密码
LoginCheckDB.DBPass = wcggame

#数据库安全保存路径
LoginCheckDB.DBSafeSavePath = ./_login_check_db

