#是否开启检测内部测试用的用户名
LoginCheckServer.NeedCheckAcc = false

#SDK登录后台相关配置
LoginCheckServer.SdkUrl = http://127.0.0.1

#SDK默认链接
LoginCheckServer.StandByLoginUrlList = []

#SDK备选链接列表
LoginCheckServer.SdkLoginUrl = /api/user/login/verify

#SDK登录验证链接
LoginCheckServer.SdkAppId = 1

#登录校验id和秘钥
LoginCheckServer.SdkKey = test

#时区信息
LoginCheckServer.TimeZone = GMT+8:00

