#数据库主机地址
ScheduleLogDB.DBHost = 127.0.0.1

#数据库名称
ScheduleLogDB.DBName = gom_schedule_log

#数据库用户名
ScheduleLogDB.DBUser = wcggame

#数据库密码
ScheduleLogDB.DBPass = wcggame

#数据库安全保存路径
ScheduleLogDB.DBSafeSavePath = ./_schedule_log_db

