#数据库主机地址
ShareCodeDB.DBHost = 127.0.0.1

#数据库名称
ShareCodeDB.DBName = gom_share_code

#数据库用户名
ShareCodeDB.DBUser = wcggame

#数据库密码
ShareCodeDB.DBPass = wcggame

#数据库安全保存路径
ShareCodeDB.DBSafeSavePath = ./_share_code_db

