#登录服务器是否开启作弊登录
LoginServer.CheatEnterEnable = true

#登录服务器对应的地域标记
LoginServer.AreaTag = common

#登录服务器在登录服务器类型中的类型Id，不同Login服务器的本Id必须不同
LoginServer.LoginTypeId = 1

#客户端连接端口
LoginServer.ConnectPort = 5101

#客户端连接缓冲区大小
LoginServer.ClientSocketCacheSize = 102400

#时区信息
LoginServer.TimeZone = GMT+8:00

