#登录聊天服使用的系统标识
ChatSDK.SystemTag = np_interface_chat_system

#登录聊天服使用的系统ID
ChatSDK.SystemId = 1

#客户端连接Ip
ChatSDK.ConnectIp = 127.0.0.1

#客户端连接端口
ChatSDK.ConnectPort = 7900

#客户端连接用户
ChatSDK.ConnectUser = tp_chat_user

#客户端连接密码
ChatSDK.ConnectPassword = tp_chat_password

