#数据库主机地址
InterfaceLogDB.DBHost = 127.0.0.1

#数据库名称
InterfaceLogDB.DBName = gom_interface_log

#数据库用户名
InterfaceLogDB.DBUser = wcggame

#数据库密码
InterfaceLogDB.DBPass = wcggame

#数据库安全保存路径
InterfaceLogDB.DBSafeSavePath = ./_interface_log_db

