#数据库主机地址
InterfaceDB.DBHost = 127.0.0.1

#数据库名称
InterfaceDB.DBName = gom_interface

#数据库用户名
InterfaceDB.DBUser = wcggame

#数据库密码
InterfaceDB.DBPass = wcggame

#数据库安全保存路径
InterfaceDB.DBSafeSavePath = ./_interface_db

