package NPEnum;

/*********
 * 游戏事件类型
 **/
public enum ENPGameEvent {
	NONE, //0 ==== 
	GM_CMD, //1 ==== GM 命令
	REMOTE_EFFECT, //2 ==== 异步远程效果
	MOTION_OPEN, //3 ==== 开启热情状态
	HERO_LEVEL_UP, //4 ==== 英雄升级
	HERO_STAR_UP, //5 ==== 英雄升星
	HERO_SKILL_UP, //6 ==== 英雄升技能
	HERO_AUTO_GIVE, //7 ==== 英雄自动给予的军队信息
	SOLDIER_LEVEL_UP, //8 ==== 士兵升级
	SOLDIER_STAR_UP, //9 ==== 士兵升星
	SOLDIER_SKILL_UP, //10 ==== 士兵升技能
	ITEM_PRODUCT, //11 ==== 物品产出
	BUFF_EXPIRED, //12 ==== buff移除
	CORSSDAY_LOGIN, //13 ==== 跨天登录
	HERO_UNLOCK, //14 ==== 英雄解锁
	SOLDIER_UNLOCK, //15 ==== 士兵解锁
	SELL_BAG_ITEM, //16 ==== 出售背包物品
	USE_BAG_ITEM, //17 ==== 使用背包物品
	OPEN_DROP, //18 ==== 打开掉落物品
	DROP_EXPIRED, //19 ==== 掉落移除
	MINION_CARD_UPGRADE_LVL, //20 ==== 兵种卡牌升级
	MINION_CARD_UPGRADE_STAR, //21 ==== 兵种卡牌升星
	MINION_CARD_UNLOCK, //22 ==== 兵种卡牌解锁
	PLAYER_LEVE_UP, //23 ==== 玩家升级
	PLAYER_INIT, //24 ==== 玩家初始化
	HANGUP_END, //25 ==== 挂机结束
	BOSS_END, //26 ==== 挑战结束
	GAIN_MAIL_REWARD, //27 ==== 获取邮件奖励
	FINISH_ALL_MAIL, //28 ==== 完成所有邮件（一键领取）
	DEL_MAIL, //29 ==== 删除邮件
	DEL_ALL_MAIL, //30 ==== 删除所有邮件（一键删除）
	REFRESH_MAIL, //31 ==== 刷新邮件
	MAIL_TAKE_ALL, //32 ==== 一键获取所有邮件
	MAIL_READ_ONE, //33 ==== 读取单封邮件
	PLAYER_RENAME, //34 ==== 玩家重命名
	RANK_LIKE, //35 ==== 排行榜点赞
	QUEST_GAIN, //36 ==== 任务获取物品
	QUEST_START, //37 ==== 开启任务
	QUEST_FINISH, //38 ==== 完成任务
	QUEST_DROP, //39 ==== 放弃任务
	QUEST_CLIENT_TRIGGER, //40 ==== 客户端驱动任务变动
	MINI_GAME_START, //41 ==== 小游戏开始
	MINI_GAME_DONE, //42 ==== 小游戏结束
	DAILY_QUEST_REFRESH, //43 ==== 日常任务刷新
	MINI_GAME_REFRESH_SINGLE, //44 ==== 悬赏任务单个刷新
	MINI_GAME_QUEST_QUICK_FINISH, //45 ==== 悬赏任务快速完成
	CLOCK_REWARD, //46 ==== 定时发放奖励
	MINI_GAME_QUEST_START, //47 ==== 悬赏任务开始
	SEND_FRIEND_APPLY, //48 ==== 发起好友申请
	AGREE_FRIEND_APPLY, //49 ==== 同意好友申请
	REFUSE_FRIEND_APPLY, //50 ==== 拒绝好友申请
	REMOVE_FRIEND, //51 ==== 移除好友
	FRIEND_APPLY_EXPIRED, //52 ==== 好友申请过期
	DONE_ACHIEVE_STEP, //53 ==== 完成成就步骤
	GAIN_ACHIEVE_POINT_REWARD, //54 ==== 领取成就点奖励
	DEAL_OFFLINE_GM, //55 ==== 处理离线GM命令
	SHOP_BUY, //56 ==== 商店购买
	SHOP_FREE_REFRESH, //57 ==== 商店免费刷新
	SHOP_REFRESH, //58 ==== 商店刷新
	OFFLINE_REWARD_TAKE, //59 ==== 领取离线奖励
	OFFLINE_REWARD_LIST_TAKE, //60 ==== 领取批量离线奖励
	SLOT_MACHINE_LOTTERY, //61 ==== 老虎机抽奖
	STELLA_GET_STEP_REWARD, //62 ==== 领取星座阶段奖励
	PVE_RES_GAIN_ITEM, //63 ==== 领取关卡产出
	PVE_GAIN_ALL_CHAPTER_REWARD, //64 ==== 领取所有章节奖励
	BOX_GAIN_ITEM, //65 ==== 领取宝箱礼物
	SET_DEFAULT, //66 ==== 设置默认
	LAZY_CD_APPLY, //67 ==== lazycd自然恢复
	DAILY_QUEST_FINISH, //68 ==== 日常任务完成
	DAILY_QUEST_ACTIVE_GAIN, //69 ==== 日常任务活跃度奖励领取
	MINI_GAME_QUEST_FINISH, //70 ==== 悬赏任务完成
	FRIEND_BE_WATERED_TAKE_REWARD, //71 ==== 被好友浇水领取奖励
	FRIEND_BE_WATERED_TAKE_ALL_REWARD, //72 ==== 被好友浇水领取全部奖励
	ALL_SEVER_MAIL_CHG, //73 ==== 全服邮件变更
	PHP_OPTION, //74 ==== 后台操作
	ITEM_CONVERT, //75 ==== 背包物品兑换
	HAPPY_VALUE_TAKE_STEP_REWARD, //76 ==== 领取阶段值奖励
	WISH_QUEST_QUICK_FINISH, //77 ==== 心愿任务快速完成
	WISH_QUEST_FINISH, //78 ==== 心愿任务完成
	WISH_QUEST_ACCEPT, //79 ==== 接受心愿任务
	PVE_TAKE_CHAPTER_STEP_REWARD, //80 ==== 领取章节阶段奖励
	PVE_TAKE_CHAPTER_ALL_REWARD, //81 ==== 领取章节所有奖励
	PLAYER_INIT_SET_NAME, //82 ==== 玩家初始化设置名称
	CHANGE_PREFAB, //83 ==== 修改玩家外形
	PLAYER_STAGE_UPGRADE, //84 ==== 玩家段位升阶
	ON_PLAYER_PROPERTY_CHG, //85 ==== 玩家属性变化触发
	PLAYER_CREATE, //86 ==== 玩家创角
	TEMP_RANK_SETTLE, //87 ==== 临时冲榜结算
	SIGN_IN, //88 ==== 签到
	DRAW_SIGN_IN_STEP_REWARD, //89 ==== 领取签到阶段奖励
	RANK_SET_OBJ_SCORE, //90 ==== 排行榜设置obj分数
	BUILDING_BUILD, //91 ==== 建筑-创建建筑
	BUILDING_UPGRADE_LVL, //92 ==== 建筑-升级建筑
	BUILDING_FARM_CLICK, //93 ==== 建筑-农田建筑点击收益
	BUILDING_BUSINESS_HIRE, //94 ==== 建筑-经营建筑雇佣
	CONSORT_UP_FETTERS_LVL, //95 ==== 家人升级羁绊等级
	CONSORT_UP_BUSINESS_SKILL, //96 ==== 家人领悟经营技能
	CONSORT_UP_BLESS_SKILL, //97 ==== 家人升级加护技能
	CONSORT_SET_CUR_SKIN, //98 ==== 家人设置当前穿戴皮肤
	CONSORT_APPOINT_TRAVEL, //99 ==== 家人指定出游
	CONSORT_RND_CALL, //100 ==== 家人随机邀约
	CONSORT_AKEY_CALL, //101 ==== 家人一键邀约
	CONSORT_TRAVEL_REFRESH, //102 ==== 家人出游数据刷新
	CONSORT_UP_HALO, //103 ==== 家人升级星辉
	CONSORT_GET_CG_REWARD, //104 ==== 家人领取CG解锁奖励
	CONSORT_UNLOCK_SKIN, //105 ==== 家人解锁皮肤
	CONSORT_UNLOCK_HALO, //106 ==== 家人解锁星辉
	CHILD_SET_NAME, //107 ==== 子嗣设置名称
	CHILD_TRAIN, //108 ==== 子嗣上课
	CHILD_GRADUATE, //109 ==== 子嗣毕业
	CHILD_SET_STEP, //110 ==== 子嗣设置阶段
	CHILD_SEAT_ADD_ENERGY, //111 ==== 子嗣训练位增加脑力值
	ADULT_SEND_PLAYER_APPLY, //112 ==== 子嗣联姻发送指定联姻请求
	ADULT_CANCEL_PLAYER_APPLY, //113 ==== 子嗣联姻取消指定联姻请求
	ADULT_REFUSE_PLAYER_APPLY, //114 ==== 子嗣联姻拒绝联姻请求
	ADULT_REFUSE_ALL_PLAYER_APPLY, //115 ==== 子嗣联姻拒绝所有联姻请求
	ADULT_AGREE_PLAYER_APPLY, //116 ==== 子嗣联姻同意联姻请求
	ADULT_CHECK_POOL_APPLY, //117 ==== 子嗣联姻检查联姻池请求
	ADULT_SEND_POOL_APPLY, //118 ==== 子嗣联姻发送全服联姻请求
	ADULT_AGREE_POOL_APPLY, //119 ==== 子嗣联姻同意联姻池请求
	ADULT_CANCEL_POOL_APPLY, //120 ==== 子嗣联姻取消联姻池请求
	HERO_UPGRADE, //121 ==== 大臣升级
	HERO_SET_SKIN, //122 ==== 大臣设置皮肤
	HERO_BUSINESS_SKILL_UPGRADE, //123 ==== 大臣经营技能升级
	HERO_STEP_UPGRADE, //124 ==== 大臣阶段提升
	HERO_SKIN_UPGRADE, //125 ==== 大臣皮肤升级
	HERO_TALENT_SKILL_UPGRADE, //126 ==== 大臣资质技能升级
	HERO_SKIN_UNLOCK, //127 ==== 大臣皮肤解锁
	HERO_STAR_UPGRADE, //128 ==== 英雄升星
	COLLEGE_START_STUDY, //129 ==== 大学开始学习
	COLLEGE_FINISH_STUDY, //130 ==== 大学结束学习
	COLLEGE_A_KEY_START_STUDY, //131 ==== 大学开始学习
	COLLEGE_A_KEY_FINISH_STUDY, //132 ==== 大学结束学习
	COLLEGE_UNLOCK_SEAT, //133 ==== 大学解锁座位
	HERO_HALO_UNLOCK, //134 ==== 大臣光环解锁
	HERO_HALO_UPGRADE, //135 ==== 大臣光环升级
	DINNER_TICK, //136 ==== 宴会TICK
	DINNER_START, //137 ==== 宴会开启
	DINNER_TAKE_OWNER_RESULT, //138 ==== 获取开宴结算数据
	DINNER_JOIN, //139 ==== 赴宴
	DINNER_CHECK_NPC, //140 ==== 宴会NPC赴宴检查
	DINNER_RETURN, //141 ==== 宴会返回补偿
	CHAPTER_ROLL_DICE, //142 ==== 关卡摇色子
	CHAPTER_A_KEY_DEAL_EVENT, //143 ==== 关卡一键处理事件
	CHAPTER_DEAL_PVE_EVENT, //144 ==== 关卡处理PVE事件
	CHAPTER_DEAL_BOSS_EVENT, //145 ==== 关卡处理BOSS事件
	CHAPTER_DEAL_BOSS_EVENT_HERO_RELIVE, //146 ==== 关卡处理BOSS事件大臣恢复
	CHAPTER_DEAL_COMMON_EVENT, //147 ==== 关卡处理普通事件
	TAKE_ANECDOTE_REWARD, //148 ==== 领取政务奖励
	TAKE_ALL_ANECDOTE_REWARD, //149 ==== 领取全部政务奖励
	RECOVER_ANECDOTE_SUM, //150 ==== 恢复政务数量
	AVATAR_GACHA_ROLL, //151 ==== AVATAR抽卡
	DAILY_CHECK, //152 ==== 每日签到
	DAILY_CHECK_DRAW_REWARD, //153 ==== 每日签到领取奖励
	TRAVEL_START, //154 ==== 游历-开始游历
	TRAVEL_DEAL, //155 ==== 游历-处理事件
	TRAVEL_AKEY_DEAL, //156 ==== 游历-一键处理事件
	HERO_RECOMMEND_DEAL, //157 ==== 大臣推荐事件处理
	HERO_RECOMMEND_DEL, //158 ==== 大臣推荐事件移除
	LEVY_SPEED_CHG, //159 ==== 征收速度变化
	LEVY_SETTLE, //160 ==== 征收结算
	LEVY_COLLECT, //161 ==== 征收采集产出
	LEVY_OFFLINE_SETTLE, //162 ==== 征收离线结算
	MARKET_UPGRADE_LVL, //163 ==== 集市升级
	MARKET_OPERATE, //164 ==== 集市经营
	MARKET_OPERATE_BY_COST_ITEM, //165 ==== 集市经营（消耗物品）
	MARKET_AKEY_OPERATE, //166 ==== 集市一键经营
	CHAPTER_DEAL_DIALOG_EVENT, //167 ==== 关卡处理对话事件
	SEND_CHAT_TO_ROOM, //168 ==== 聊天频道发言
	DONE_FUNC_UNLOCK, //169 ==== 完成功能解锁
	RANK_FIXED_LIKE, //170 ==== 常驻排行榜点赞
	MAX_NATION_POWER_CHG, //171 ==== 最大国力变更
	TOP_HERO_CHG, //172 ==== 最强大臣变更
	RANK_FIXED_A_KEY_LIKE, //173 ==== 常驻排行榜一键点赞
	ZONE_ACTIVITY_SCHEDULE_REG, //174 ==== 排期活动注册
	GAIN_VISIT_OTHER_PLAYER_REWARD, //175 ==== 获取拜访其他玩家奖励
	CHAPTER_DEAL_TREASURE_BOX, //176 ==== 关卡处理宝箱事件
	ACTIVITY_STEP_REWARD_SEND_MAIL, //177 ==== 活动阶段奖励补发邮件
	ACTIVITY_RANK_REWARD_SEND_MAIL, //178 ==== 活动排行榜奖励补发邮件
	PLAYER_LOGIC_OFFLINE, //179 ==== 玩家逻辑下线
	PLAYER_LOGIC_ONLINE, //180 ==== 玩家逻辑上线
	ACTIVE_WEEK_CARD_FREE_TRIAL, //181 ==== 激活周卡免费试用
	SHIELD_PLAYER_ADD, //182 ==== 增加屏蔽玩家
	DRAW_ACTIVITY_RANK_REWARD, //183 ==== 领取活动排行榜奖励
	DRAW_ACTIVITY_STEP_REWARD, //184 ==== 领取活动阶段奖励
	ACTIVITY_CLOSE, //185 ==== 活动关闭
	DRAW_QUESTIONNAIRE_REWARD, //186 ==== 领取问卷奖励
	PLAYER_DETAIL_LIKE, //187 ==== 玩家详情点赞
	TAKE_STAGE_GOAL_TASK_REWARD, //188 ==== 领取阶段任务完成奖励
	GUILD_CONSTRUCT, //189 ==== 联盟建设
	CHANGE_GUILD_NAME, //190 ==== 联盟改名
	CREATE_GUILD, //191 ==== 创建联盟
	CHANGE_GUILD_FLAG, //192 ==== 联盟改旗
	CHANGE_GUILD_POSITION, //193 ==== 联盟职位变更
	GUILD_UPGRADE, //194 ==== 联盟升级
	JOIN_GUILD, //195 ==== 加入联盟
	LEAVE_GUILD, //196 ==== 退出联盟
	GUILD_BROADCAST_MESSAGE, //197 ==== 联盟广播消息
	CHAPTER_FORWARD, //198 ==== 关卡前进
	CHAPTER_ATTACK_BOSS, //199 ==== 关卡攻击BOSS
	CHAPTER_INSPIRE, //200 ==== 关卡鼓舞
	EQUIP_UPGRADE, //201 ==== 藏品升级
	EQUIP_SKILL_RESHAPE, //202 ==== 藏品技能重塑
	EQUIP_DISASSEMBLE, //203 ==== 藏品分解
	EQUIP_AWAKEN, //204 ==== 藏品觉醒
	EQUIP_SKILL_RESHAPE_ACTIVE, //205 ==== 藏品技能重塑激活
	EQUIP_SKILL_RESHAPE_ABANDON, //206 ==== 藏品技能重塑放弃
	EQUIP_WEAR, //207 ==== 藏品穿戴
	EQUIP_TAKE_OFF, //208 ==== 藏品卸下
	EQUIP_LOCK_CHG, //209 ==== 藏品锁定状态变更
	RECRUIT, //210 ==== 兑换
	STATION_UPGRADE, //211 ==== 贸易站升级
	STATION_COLLECT, //212 ==== 贸易站收集
	ARENA_SELECT_ATTACK, //213 ==== 竞技场指定攻击
	ARENA_CHOOSE_BUFF, //214 ==== 竞技场选择buff
	ARENA_ROUND_ATTACK, //215 ==== 竞技场回合攻击
	ARENA_BUY_ATTACK_TIMES, //216 ==== 竞技场购买攻击次数
	ARENA_AKEY_ATTACK, //217 ==== 竞技场一键攻击
	DRAW_TARGET_REWARD, //218 ==== 领取目标奖励
	CLIENT_REQ_REFRESH, //219 ==== 客户端请求刷新
	DEAL_ANECDOTE_CHOICE_EVENT, //220 ==== 处理政务选项事件
	DEAL_ANECDOTE_REWARD_EVENT, //221 ==== 处理政务奖励事件
	DEAL_ANECDOTE_EARNINGS_EVENT, //222 ==== 处理政务赚速事件
	MAX_POWER_CHG, //223 ==== 最大战力变更
	MAX_EARNINGS_CHG, //224 ==== 最大赚速变更
	RECORD_UPDATE, //225 ==== 记录修改
	DRAW_DAILY_REWARD, //226 ==== 领取每日奖励
	TOWER_ATTACK, //227 ==== 爬塔击败
	DRAW_GUILD_ACTIVE_BOX, //228 ==== 领取联盟活跃宝箱
	DRAW_GUILD_GREAT_REWARD, //229 ==== 领取联盟大礼
	DRAW_GUILD_CONSTRUCT_REWARD, //230 ==== 领取联盟建设奖励
	DEAL_ENTRUST, //231 ==== 处理委托
	ARENA_RANDOM_ATTACK, //232 ==== 竞技场随机攻击
	MIDDAY_DUNGEON_ATTACK, //233 ==== 午间副本攻击
	MIDDAY_DUNGEON_BORROW_ATTACK, //234 ==== 午间副本借用攻击
	MIDDAY_DUNGEON_BOX_DROP, //235 ==== 午间副本宝箱掉落
	MIDDAY_DUNGEON_BOX_DRAW, //236 ==== 午间副本宝箱领取
	EVENING_DUNGEON_ATTACK, //237 ==== 晚间副本攻击
	EVENING_DUNGEON_BOSS_KILLED, //238 ==== 晚间副本BOSS被击杀
	EVENING_DUNGEON_RANK_SETTLE, //239 ==== 晚间副本排行榜结算
	TITLE_SET_SHOW, //240 ==== 称号是否展示
	TITLE_SET_CUR, //241 ==== 设置当前穿戴称号
	COMBO_TITLE_UNLOCK, //242 ==== 组合称号解锁
	PLAYER_SKIN_UNLOCK, //243 ==== 玩家皮肤解锁
	PLAYER_SKIN_UP_LVL, //244 ==== 玩家皮肤升级
	DRAW_SEVEN_DAYS_LOGIN_REWARD, //245 ==== 领取七天登录奖励
	DRAW_EARNINGS_GOAL_REWARD, //246 ==== 领取赚速目标奖励
	DRAW_EARNINGS_GOAL_HONOR_REWARD, //247 ==== 领取赚速目标荣誉奖励
	DRAW_SEVEN_DAY_GOALS_TASK_REWARD, //248 ==== 领取七天目标任务奖励
	DRAW_SEVEN_DAY_GOALS_STEP_REWARD, //249 ==== 领取七天目标阶段奖励
	BUY_ACTIVITY_SHOP_ITEM, //250 ==== 购买活动商店物品
	BUY_ACTIVITY_CRYSTAL_GIFT_PACK, //251 ==== 购买活动钻石礼包
	ACTIVITY_ITEM_EXPIRED, //252 ==== 活动关联物品过期
	SET_PREFAB, //253 ==== 设置预设
	DRAW_CONSORT_DIALOGUE_REWARD, //254 ==== 领取家人对话奖励
	CONSORT_INTIMACY_CHG, //255 ==== 家人亲密度变化
	TAKE_STAGE_GOAL_BIG_STEP_REWARD, //256 ==== 领取阶段任务大阶段完成奖励
	DRAW_COUNTDOWN_EVENT_REWARD, //257 ==== 领取倒计时事件奖励
	RAND_GAIN_CHILD, //258 ==== 随机获得子嗣
	INN_RECEIVE_GUEST, //259 ==== 旅店接待客人
	INN_BUILD_STATION, //260 ==== 旅店建造设施
	INN_STATION_UPGRADE, //261 ==== 旅店设施升级
	INN_UNLOCK_DISH, //262 ==== 旅店解锁菜品
	INN_DISH_UPGRADE, //263 ==== 旅店菜品升级
	INN_SETTLE, //264 ==== 旅店结算
	INN_GIFT_UPGRADE, //265 ==== 旅店珍宝升级
	INN_GIFT_ACTIVE, //266 ==== 旅店珍宝激活
	INN_SERVE_SPECIAL_GUEST, //267 ==== 旅店接待特殊客人
	INN_DRAW_GUEST_HANDBOOK_REWARD, //268 ==== 旅店领取客人图鉴奖励
	INN_DRAW_SPECIAL_GUEST_HANDBOOK_REWARD, //269 ==== 旅店领取特殊客人图鉴奖励
	INN_DRAW_SPECIAL_GUEST_MUSEUM_ITEM, //270 ==== 旅店领取特殊客人博物馆物品
	INN_MEDAL_UPGRADE, //271 ==== 旅店奖牌升级
	DRAW_CHAPTER_PLOT_REWARD, //272 ==== 领取关卡剧情奖励
	DEAL_HIRE_EMPLOYEE_PLOT, //273 ==== 雇佣员工剧情
	TOWER_RESEARCH_ACTIVE, //274 ==== 爬塔研究激活
	TOWER_DRAW_RESEARCH_REWARD, //275 ==== 爬塔研究奖励领取
	TOWER_BEEN_DEFEATED, //276 ==== 爬塔被击败
	DRAW_SYSTEM_QUEST_STEP_REWARD, //277 ==== 领取系统任务阶段奖励
	SYSTEM_QUEST_CLIENT_ADD_COUNT, //278 ==== 系统任务客户端增加计数
	INN_UNLOCK_GUEST, //279 ==== 旅店解锁客人
	TREASURE_HUNT_CAPTURE, //280 ==== 寻宝捕捉
	TREASURE_HUNT_ORE_SKILL_ACTIVE, //281 ==== 寻宝矿石技能激活
	TREASURE_HUNT_ORE_SKILL_UPGRADE, //282 ==== 寻宝矿石技能升级
	TREASURE_HUNT_TREASURE_SKILL_ACTIVE, //283 ==== 寻宝奇物技能激活
	TREASURE_HUNT_TREASURE_SKILL_UPGRADE, //284 ==== 寻宝奇物技能升级
	TREASURE_HUNT_COMPOSITE_SKILL_ACTIVE, //285 ==== 寻宝组合技能激活
	TREASURE_HUNT_DRAW_ORE_RECORD_REWARD, //286 ==== 寻宝领取矿石记录奖励
	TREASURE_HUNT_DRAW_CAPTURE_POWER, //287 ==== 寻宝领取捕捉能量道具
	TREASURE_HUNT_TRANS_ORE, //288 ==== 寻宝转换矿石
	TREASURE_HUNT_DRAW_DAILY_GEM, //289 ==== 寻宝领取每日钻石
	GRAVE_CELEBRATE, //290 ==== 杰出者大厅膜拜杰出者
	GRAVE_CONGRATULATE, //291 ==== 杰出者大厅祝贺新晋杰出者
	GUILD_DUNGEON_SET_AUTO_START, //292 ==== 设置自动开启公会副本
	GUILD_DUNGEON_START, //293 ==== 开启公会副本
	GUILD_DUNGEON_AUTO_START, //294 ==== 自动开启公会副本
	GUILD_DUNGEON_AUTO_SETTLE, //295 ==== 自动结算公会副本
	GUILD_DUNGEON_UPGRADE_LVL, //296 ==== 公会副本升级
	GUILD_DUNGEON_ATTACK_MONSTER, //297 ==== 公会副本攻击怪物
	GUILD_DUNGEON_RECOVER_FIGHT, //298 ==== 公会副本恢复出战次数
	GUILD_DUNGEON_GAIN_ALL_REWARD, //299 ==== 公会副本领取所有奖励
	GUILD_DUNGEON_START_FAIL, //300 ==== 公会副本开启失败
	GUILD_DUNGEON_UPGRADE_FAIL, //301 ==== 公会副本升级失败
	GUILD_DUNGEON_ATTACK_FAIL, //302 ==== 公会副本攻击失败
	MARS_GO_ROUTE_START_STAGE, //303 ==== 前往火星开启
	MARS_GO_ROUTE_DONE_STAGE, //304 ==== 前往火星完成阶段
	MARS_PEOPLE_IMMIGRANT, //305 ==== 火星居民-移民
	MARS_PEOPLE_CONFIRM_IMMIGRANT, //306 ==== 火星居民-确认移民
	MARS_PEOPLE_USE_INTELLIGENT, //307 ==== 火星居民-使用决策
	MARS_PEOPLE_DEAL_HELP_REWARD, //308 ==== 火星居民-处理奖励帮助
	MARS_PEOPLE_DEAL_CHOICE_REWARD, //309 ==== 火星居民-处理选择帮助
	MARS_PEOPLE_TICK, //310 ==== 火星居民-tick处理
	MARS_BUILDING_CREATE, //311 ==== 火星建筑-请求创建
	MARS_BUILDING_UPGRADE_LVL, //312 ==== 火星建筑-请求升级
	MARS_BUILDING_HOME_SET, //313 ==== 火星建筑-设置主基地配置
	MARS_BUILDING_PEOPLE_DISPATCH, //314 ==== 火星建筑-派遣居民
	MARS_BUILDING_EQUIPMENT_UPGRADE, //315 ==== 火星建筑-部件升级
	MARS_BUILDING_CREATE_CONFIRM, //316 ==== 火星建筑-创建确认
	MARS_BUILDING_UPGRADE_CONFIRM, //317 ==== 火星建筑-升级确认
	MARS_BUILDING_UPGRADE_CANCEL, //318 ==== 火星建筑-升级取消
	MARS_BUILDING_GAIN_ALL_ENERGY, //319 ==== 火星建筑-获取全部建筑产出能量
	MARS_BUILDING_SET_DONE, //320 ==== 火星建筑-设置立即完成
	MARS_BUILDING_HOME_POWER_CHG, //321 ==== 火星建筑-主基地开关变化
	MARS_BUILDING_FOOD_POWER_CHG, //322 ==== 火星建筑-FOOD开关变化
	MARS_TECH_UPGRADE_LVL, //323 ==== 火星科技-请求升级
	MARS_TECH_UPGRADE_LVL_CONFIRM, //324 ==== 火星科技-升级确认
	MARS_TECH_UPGRADE_CANCEL, //325 ==== 火星科技-升级取消
	MARS_TECH_SET_DONE, //326 ==== 火星科技-一键完成下一个阶段
	MARS_EXPLORE_UPGRADE_LVL, //327 ==== 火星探险-升级
	MARS_EXPLORE_TEAM_SET_HERO, //328 ==== 火星探险-队伍设置大臣
	MARS_EXPLORE_TEAM_SET_NAME, //329 ==== 火星探险-队伍设置名称
	MARS_EXPLORE_START_DEAL, //330 ==== 火星探险-开始探险
	MARS_EXPLORE_EVENT_GET_DONE_REWARD, //331 ==== 火星探险-获取战斗完成奖励
	MARS_EXPLORE_TEAM_START_REPAIR, //332 ==== 火星探险-队伍开始维修
	MARS_EXPLORE_FORWARD_COLLECT_MINE, //333 ==== 火星探险-前往采集
	MARS_EXPLORE_TEAM_ENTER_MINE, //334 ==== 火星探险-队伍到达矿产
	MARS_EXPLORE_COLLECT_END, //335 ==== 火星探险-采集结束
	MARS_EXPLORE_TEAM_BACK_DONE, //336 ==== 火星探险-队伍返回基地
	MARS_MINE_CHECK, //337 ==== 火星探险-火星矿检查
	MARS_POWER_CHG, //338 ==== 火星实力变化
	MARS_TEAM_POWER_CHG, //339 ==== 火星队伍实力变化
	MARS_EXPLORE_TEAM_STATUS_CHG, //340 ==== 火星队伍状态发生改变
	MARS_ADD_TEMP_BUILD_QUEUE, //341 ==== 火星建筑-增加临时建造队列
	MARS_POWER_CHECK, //342 ==== 火星实力计算
	MARS_BUILDING_PEOPLE_DISPATCH_SUM_CAL, //343 ==== 火星建筑-派遣居民总数计算
	CREATE_ORDER, //344 ==== 创建订单
	CLIENT_NOTIFY_ORDER_PAY, //345 ==== 客户端通知订单支付
	CLIENT_CANCEL_ORDER, //346 ==== 客户端取消订单
	GIFT_PACK_REFRESH, //347 ==== 礼包刷新
	GIFT_PACK_BUY, //348 ==== 礼包购买
	GUILD_DUNGEON_GAIN_REWARD, //349 ==== 公会副本领取奖励
	ORDER_VOUCHER_PAY, //350 ==== 订单代金券支付
	PLAT_NOTIFY_ORDER_PAY, //351 ==== 平台通知订单支付
	TAKE_STAGE_GOAL_FIRST_REACH_REWARD, //352 ==== 领取阶段任务首次到达奖励
	GUILD_COOPERATE_DRAW_REWARD_POINT_REWARD, //353 ==== 联盟协作领取奖励点奖励
	GUILD_COOPERATE_ATTACK, //354 ==== 联盟协作攻击
	GUILD_COOPERATE_RECOVER_HERO, //355 ==== 联盟协作恢复大臣
	DRAW_VIP_LEVEL_REWARD, //356 ==== 领取VIP等级奖励
	DRAW_VIP_LEVEL_RECHARGE_REWARD, //357 ==== 领取VIP等级充值奖励
	DRAW_FIRST_RECHARGE_REWARD, //358 ==== 领取首充奖励
	TRAVEL_GAIN_CONSORT, //359 ==== 游历-获取家人
	CHAPTER_GAIN_CONSORT, //360 ==== 关卡-获取家人
	USE_BAG_ITEM_FOR_TIME_REDUCE, //361 ==== 使用减少时间道具
	OFFLINE_REWARD_DEAL, //362 ==== 离线处理
	DRAW_RECHARGE_REBATE_REWARD, //363 ==== 领取充值返利奖励
	SERVER_CROSS_DAY, //364 ==== 服务器跨天处理
	WEB_PAY_BATCH_CREATE_ORDER, //365 ==== 网页支付批量创建订单
	ORDER_DELIVERY, //366 ==== 订单发货
	PRIVILEGE_CARD_GAIN_DAILY_REWARD, //367 ==== 权益卡领取当日奖励
	PRIVILEGE_CARD_AUTO_SETTLE, //368 ==== 权益卡自动结算
	ITEM_EXPIRED_MAIL_SEND, //369 ==== 过期物品补偿邮件下发
	CONSORT_AI_CHAT_INTERACT, //370 ==== 家人AI聊天发送/扣费操作
	HERO_BUILDING_PLACE, //371 ==== 英雄驻守建筑
	HERO_BUILDING_REMOVE, //372 ==== 英雄撤离建筑
	GUILD_LEADER_TRANSFER_MANUAL, //373 ==== 会长主动转让
	GUILD_LEADER_PASSIVE_TRANSFER_OFFLINE, //374 ==== 会长离线超时被动转让
	GUILD_LEADER_PASSIVE_TRANSFER_IMPEACH, //375 ==== 弹劾成功被动转让
	GUILD_POSITION_APPOINT, //376 ==== 公会职位任命
	GUILD_MARS_HELP_SEND, //377 ==== 公会-发起火星求助
	GUILD_MARS_HELP_DEAL, //378 ==== 公会-处理火星求助
	GUILD_MARS_HELP_BE_DEALED, //379 ==== 公会-被其他玩家帮助
	STORE_REVIEWS_ADD, //380 ==== 增加商品评价
	STEP_REWARD_SCORE_CHG, //381 ==== 阶段奖励分数变更
	GUILD_BOX_REFRESH, //382 ==== 联盟宝箱刷新
	GUILD_BOX_SETTLE, //383 ==== 联盟宝箱结算（退出联盟）
	GUILD_BOX_DISPATCH, //384 ==== 联盟宝箱下发奖励邮件
	GUILD_BOX_GAIN_ALL_REWARD, //385 ==== 联盟宝箱领取所有奖励
	GUILD_BOX_GAIN_REWARD, //386 ==== 联盟宝箱领取指定奖励
	MARS_EXPLORE_TEAM_SET_REPAIR_DONE, //387 ==== 火星探险-设置队伍维修完成
	MARS_HOME_COLLECT, //388 ==== 主基地资源收集
	GOLD_SETTLE, //389 ==== 货币（金币）结算
	MARS_ENERGY_SETTLE, //390 ==== 货币（火星能量）结算
	MARS_ENERGY_SPEED_CHG, //391 ==== 货币（火星能量）速度变化
	MARS_EXPLORE_TEAM_CANCEL_REPAIR, //392 ==== 火星探险-取消队伍维修
	MARS_EXPLORE_TEAM_START_AND_FINISH_REPAIR, //393 ==== 火星探险-开始并完成队伍维修
	GUILD_MARS_HELP_AUTO, //394 ==== 联盟火星系统互助-玩家进入自助帮助求助玩家
	ACTIVITY_FUND_DRAW_REWARD, //395 ==== 活动基金领取奖励
	ACTIVITY_FUND_REMOVE, //396 ==== 活动基金移除
	ACTIVITY_FUND_ADD, //397 ==== 活动基金添加
	RANK_GIFT_PACK_BUY, //398 ==== 冲榜礼包购买
	RUSH_EXCHANGE, //399 ==== 限时兑换-发起兑换
	RUSH_EXCHANGE_REWARD, //400 ==== 限时兑换-领取奖励
	SEND_ACTIVITY_RANK_BOX, //401 ==== 活动排行榜宝箱发送
	CLIENT_NOTIFY_FUNC_UNLOCK, //402 ==== 客户端通知功能解锁
	LOVER_COLLECT_SET_TARGET, //403 ==== 情人收集-选择目标情人
	LOVER_COLLECT_CLAIM, //404 ==== 情人收集-领取情人
	COUNT_DOWN_EVENT_DONE, //405 ==== 完成倒计时事件
	FORBID_CHAT, //406 ==== 禁言
	LIFT_FORBID_CHAT, //407 ==== 解除禁言
	REMOTE_EVENT, //408 ==== 远程触发事件
	;
public static final ENPGameEvent[]  ENPGameEvent_Values = ENPGameEvent.values();
public static final int ENPGameEvent_Length = ENPGameEvent_Values.length;
public static ENPGameEvent ENPGameEvent_FromInt(int _ivalue) {
	if(_ivalue < 0 || _ivalue >= ENPGameEvent_Length){ return null; }
	return ENPGameEvent_Values[_ivalue];
}
}

