#数据库主机地址
GameLogicLogDB.DBHost = 127.0.0.1

#数据库名称
GameLogicLogDB.DBName = god_game_logic_log

#数据库用户名
GameLogicLogDB.DBUser = wcggame

#数据库密码
GameLogicLogDB.DBPass = wcggame

#数据库安全保存路径
GameLogicLogDB.DBSafeSavePath = ./_game_logic_log_db

