#服务器接收客户端缓存的字节长度
WCGBasicServer.RecBufferLen = 102400

#服务器在内部系统中的监听端口（注意，非外部监听端口）
WCGBasicServer.Port = 7581

#平台服务器连接IP
WCGBasicServer.PlatServerIp = 127.0.0.1

#平台服务器连接端口
WCGBasicServer.PlatServerPort = 6660

#平台服务器连接密码
WCGBasicServer.PlatServerPassword = wcg_basic_plat_server

#内部其他服务器连接本服务器时使用的IP
WCGBasicServer.InternalIp = 127.0.0.1

#内部其他服务器连接本服务器时使用的端口
WCGBasicServer.InternalPort = 7581

