#数据库主机地址
CrossTeamDB.DBHost = 127.0.0.1

#数据库名称
CrossTeamDB.DBName = gom_cross_team

#数据库用户名
CrossTeamDB.DBUser = wcggame

#数据库密码
CrossTeamDB.DBPass = wcggame

#数据库安全保存路径
CrossTeamDB.DBSafeSavePath = ./_cross_team_db

