#数据库主机地址
CrossRankLogDB.DBHost = 127.0.0.1

#数据库名称
CrossRankLogDB.DBName = gom_cross_rank_log

#数据库用户名
CrossRankLogDB.DBUser = wcggame

#数据库密码
CrossRankLogDB.DBPass = wcggame

#数据库安全保存路径
CrossRankLogDB.DBSafeSavePath = ./_cross_rank_log_db

