#数据库主机地址
CrossGameLogDB.DBHost = 127.0.0.1

#数据库名称
CrossGameLogDB.DBName = gom_cross_game_log

#数据库用户名
CrossGameLogDB.DBUser = wcggame

#数据库密码
CrossGameLogDB.DBPass = wcggame

#数据库安全保存路径
CrossGameLogDB.DBSafeSavePath = ./_cross_game_log_db

