#数据库主机地址
HttpLogDB.DBHost = 127.0.0.1

#数据库名称
HttpLogDB.DBName = gom_http_log

#数据库用户名
HttpLogDB.DBHttp = wcggame

#数据库密码
HttpLogDB.DBPass = wcggame

#数据库安全保存路径
HttpLogDB.DBSafeSavePath = ./_http_log_db

