namespace GOE
{
    /// <summary>
    /// 客户端特殊效果处理枚举
    /// </summary>
    public enum EClientSpecialDealType
    {
	    NONE, //0 ==== 
	    QUIT_ACC, //1 ==== 退出帐号
	    ENTER_EMPTY_SCENE, //2 ==== 进入一个空的UI视图，可以隐藏相关的其他UI
	    QUIT_EMPTY_SCENE, //3 ==== 退出上面的空UI视图
	    ADD_EMPTY_ONL_OP_NODE, //4 ==== 打开一个空node，一般用于触发引导或者解锁弹窗
	    DO_ROLLBACK_BY_ESC, //5 ==== 执行回退操作
	    IGNORE_ALL_INPUT, //6 ==== 屏蔽所有输入
	    OPEN_ALL_INPUT, //7 ==== 开启所有输入
	    SIMULATE_CLICK_CLOTHES_BACK_ROOT, //8 ==== 衣柜模拟点击返回根目录
	    SIMULATE_CLICK_CLOTHES_SAVE, //9 ==== 衣柜模拟点击保存
	    SIMULATE_CLICK_CHAPTER_MOVE, //10 ==== 模拟点击关卡摇骰子
	    OPEN_SET_NAME_WND, //11 ==== 打开设置名字窗口
	    SIMULATE_CLICK_HERO_LEVEL_UPGRADE, //12 ==== 模拟点击英雄升级
	    SIMULATE_RET_MAIN_QUEST_REWARD, //13 ==== 模拟领取主线任务奖励
	    SIMULATE_PAGE_RET_MAIN_QUEST_REWARD, //14 ==== 模拟页面内点击主线任务领奖
	    SIMULATE_CLICK_CONSORT_RANDOM_GREET, //15 ==== 模拟点击妃子随机宠幸
	    SIMULATE_CLICK_HERO_RECOMMEND_GET, //16 ==== 模拟点击英雄推荐获取大臣
	    MOVE_FOCUS_TO_ANECDOTE, //17 ==== （弃用，改用通用入口聚焦MAIN_CITY_FOCUS_POINT）主城移动镜头到政务入口居中
		SIMULATE_CLICK_TRAVEL, //18 ==== 模拟点击游历
	    SIMULATE_CLICK_SHOW_CHAPTER_EVENT_LIST, //19 ==== 模拟点击打开关卡事件列表
	    SIMULATE_CLICK_LEVY_SILVER, //20 ==== 模拟点击征收银币
	    SIMULATE_CLICK_HOLD_DINNER, //21 ==== 模拟点击举办宴会
	    SIMULATE_CLICK_LEVY_SOLDIER, //22 ==== 模拟点击征兵
	    SIMULATE_CLICK_OPEN_CONSORT_GIVE_GIFT, //23 ==== 模拟点击打开妃子送礼弹窗
	    SIMULATE_CLICK_MARKET_GET_REWARD, //24 ==== 模拟店铺领取奖励
	    SIMULATE_CLICK_TRAIN_CHILD, //25 ==== 模拟点击培养子嗣
	    SIMULATE_CLICK_OPEN_CHILD_SET_NAME, //26 ==== 模拟点击打开子嗣取名弹窗
	    SIMULATE_CLICK_OPEN_CHILD_TRAIN, //27 ==== 模拟点击打开子嗣培养弹窗
	    SIMULATE_CLICK_SUIT_MENU, //28 ==== 模拟点击套装菜单
        MOVE_FOCUS_TO_HERO_RECOMMEND, //29 ==== 主城移动镜头到骑士推荐入口居中，两个队列都有数据就取第一个，两个队列都没有数据就只移动镜头不出现手指引导
        SIMULATE_CLICK_SHARE_CLOTHES, //31 ==== 模拟点击分享装扮按钮
        SIMULATE_CLICK_SHARE_CLOTHES_CONFIRM, //32 ==== 模拟点击确认分享装扮按钮
        SIMULATE_CLICK_SHOW_CUSTOM_SUIT_LIST, //33 ==== 模拟点击打开自定义套装下拉列表
        SIMULATE_CLICK_ONE_DRAW_CARDS, //34 ==== 模拟点击单次抽卡
        SIMULATE_CLICK_OPEN_HERO_TRAIN, //35 ==== 模拟点击打开培养骑士窗口
        SIMULATE_CLICK_ADULT_START_MARRY, //36 ==== 模拟点击打开发起联姻窗口
        SIMULATE_CLICK_HERO_TALENT_TAB, //37 ==== 模拟点击打开骑士资质页签
        SIMULATE_OPEN_DAILY_CHECK, //38 ==== 模拟打开签到界面
		SIMULATE_CLICK_AVATAR_SCENE_NULL_RETURN, //39 ==== 模拟点击avatar场景空白处返回页签
        SIMULATE_CLICK_OPEN_MARKET_UPGRADE, //40 ==== 模拟点击打开码头升级界面
        SIMULATE_CLICK_OPEN_CONSORT_TRAVEL, //41 ==== 模拟点击打开情人出游界面
        SIMULATE_CLICK_CONSORT_TRAVEL_USE_ITEM, //42 ==== 模拟点击情人使用道具出游
        SIMULATE_CLICK_TEN_DRAW_CARDS, //43 ==== 模拟点击十连抽卡
        SIMULATE_CLICK_CHAPTER_START_FIGHT, //44 ==== 模拟点击关卡boss战出战
        SIMULATE_GAIN_SHOW_MAIL_REWARD, //45 ==== 模拟领取当前显示的邮件奖励(只有有邮件详情在显示时有效)
        SIMULATE_CLICK_OPEN_CHAPTER_LOSS_DEGREE, //46 ==== 模拟点击打开关卡面包消耗详情
        SIMULATE_CLICK_CLOTHES_ACTION_BACK, //47 ==== 模拟点击动作选择窗口返回
        SIMULATE_CLICK_CLOTHES_POSE_BACK, //48 ==== 模拟点击站姿选择窗口返回
        SIMULATE_CLICK_CLOTHES_BG_BACK, //49 ==== 模拟点击背景选择窗口返回
        SIMULATE_CLICK_CLOTHES_MAIN_BACK, //50 ==== 模拟点击衣柜窗口返回
        SIMULATE_CLICK_TRAVEL_CHANGE_EVENT_CHANGE, //51 ==== 模拟点击游历交换事件交换按钮
        SIMULATE_CLICK_TRAVEL_CHANGE_EVENT_NOT_CHANGE, //52 ==== 模拟点击游历交换事件不交换按钮
        SIMULATE_CLICK_PLAYER_LVL_UP, //53 ==== 模拟点击升级
        SIMULATE_CLICK_HERO_BUSINESS_SKILL_UPGRADE, //53 ==== 模拟点击伙伴经营技能升级
        SIMULATE_CLICK_BUILDING_BUILD_WND_BTN, //54 ==== 模拟点击建筑建造界面按钮
        SIMULATE_CLICK_BUSINESS_BUILDING_TEN_TIMES_HIRE_TOGGLE, //55 ==== 模拟点击经营建筑十次雇佣开关
        SIMULATE_CLICK_BUSINESS_BUILDING_HIRE_BTN, //56 ==== 模拟点击经营建筑雇佣按钮
        SIMULATE_CLICK_FARMING_BUILDING_UPGRADE_BTN, //57 ==== 模拟点击农场建筑升级按钮
        SIMULATE_CLICK_BUSINESS_BUILDING_HERO_SLOT, //58 ==== 模拟点击经营建筑英雄槽
        SIMULATE_CLICK_BUSINESS_BUILDING_UPGRADE_BTN, //59 ==== 模拟点击经营建筑升级按钮
        SIMULATE_CLICK_BUSINESS_BUILDING_HERO_SELECT_CONFIRM, //60 ==== 模拟点击经营建筑英雄选择确认
        SIMULATE_CLICK_QUIT_CONSORT_GIVE_GIFT, //61 ==== 模拟点击退出家人送礼页面
        SIMULATE_CLICK_CHAPTER_FORWARD, //62 ==== 模拟点击关卡前进
        TRIGGERS_DEVICE_VIBRATION, //62 ==== 触发手机振动0.5s
        SIMULATE_CLICK_CONFIRM_CHILD_SET_NAME, //63 ==== 模拟点击确认子嗣命名
        SIMULATE_CLICK_EQUIP_OPEN_SKILL_PAGE, //64 ==== 模拟点击打开藏品技能重塑页面
        SIMULATE_CLICK_EQUIP_UPGRADE, //65 ==== 模拟点击升级藏品
        SIMULATE_CLICK_EQUIP_SKILL_REBUILD, //66 ==== 模拟点击藏品技能重塑
        SIMULATE_CLICK_HERO_EQUIP_ENTRY_BTN, //67 ==== 模拟点击伙伴藏品入口按钮
        SIMULATE_CLICK_BUSINESS_BUILDING_UPGRADE_CONFIRM_BTN, //62 ==== 模拟点击经营建筑升级确认按钮
        SIMULATE_CLICK_HERO_EQUIP_INFO_STRENGTHEN_BTN, //68 ==== 模拟点击伙伴佩戴藏品信息界面强化按钮
        SIMULATE_CLICK_ARENA_RANDOM_ATTACK, //69 ==== 模拟点击打开谈判界面
        SIMULATE_CLICK_ARENA_OPEN_SELECT_HERO, //70 ==== 模拟点击打开竞技场谈判选择伙伴界面
        SIMULATE_CLICK_ARENA_OPEN_SELECT_INITIAL_BUFF, //71 ==== 模拟点击打开竞技场初始增益界面
        SIMULATE_CLICK_ARENA_SELECT_NULL_INITIAL_BUFF, //72 ==== 模拟点击选择竞技场空的初始增益
        SIMULATE_CLICK_STAGE_GOAL_MAIN_TASK_GAIN_REWARD, //73 ==== 模拟点击领取阶段任务主任务的奖励
        SIMULATE_CLICK_ARENA_START_FIGHT, //74 ==== 模拟点击竞技场开始战斗
        SIMULATE_SUMMON_ONE_DRAW,//75 ==== 模拟召唤单抽
        SIMULATE_SUMMON_TEN_DRAW,//76 ==== 模拟召唤十抽
        SIMULATE_CLICK_EQUIP_CONFIRM_REBUILD,//77 ==== 模拟点击藏品确认重塑
        SIMULATE_CLICK_BUSINESS_BUILDING_SET_HERO_BTN, //78 ==== 模拟点击经营建筑设置大臣按钮
        SIMULATE_CLICK_BUSINESS_BUILDING_RND_BTN, //79 ==== 模拟点击经营建筑研发按钮
        SIMULATE_CLICK_COUNTDOWN_EVENT_GET_REWARD, //80 ==== 模拟点击领取倒计时事件奖励按钮
        TRY_CHECK_SIMPLE_GUIDE, //81 ==== 尝试触发简单引导
        SIMULATE_CLICK_CONSORT_NORMAL_COMPREHEND, //82 ==== 模拟点击情人普通领悟按钮
        SIMULATE_CLICK_SCHOOL_GET_CHILD, //83 ==== 模拟点击学校招生按钮
        FORCE_RESET_SIMPLE_GUIDE, //84 ==== 强制重置简单引导
        SIMULATE_CLICK_INN_MAIN_STATION_BUTTON, //84 ==== 模拟点击旅店设施按钮
        SIMULATE_CLICK_INN_STATION_BUILD_BUTTON, //95 ==== 模拟点击旅店设施建造按钮
        SIMULATE_CLICK_INN_STATION_LEVEL_UP_BUTTON, //96 ==== 模拟点击旅店设施升级按钮
        SIMULATE_CLICK_INN_MAIN_MENU_BUTTON, //97 ==== 模拟点击旅店主界面菜单按钮
        SIMULATE_CLICK_INN_DISH_UNLOCK_BUTTON, //99 ==== 模拟点击旅店菜品解锁按钮
        SIMULATE_CLICK_INN_DISH_LEVEL_UP_BUTTON, //100 ==== 模拟点击旅店菜品升级按钮
        SIMULATE_CLICK_INN_CASH_REGISTER, //101 ==== 模拟点击旅店收银台
        SIMULATE_CLICK_INN_CREATE_GUEST_BUTTON, //102 ==== 模拟点击旅店创建客人按钮
        SIMULATE_CLICK_SYSTEM_QUEST_GET_REWARD, //103 ==== 模拟点击系统任务领取奖励按钮
        SIMULATE_CLICK_SYSTEM_QUEST_DETAIL_BUTTON, //104 ==== 模拟点击系统任务详情按钮
        SIMULATE_TRIGGER_INN_CASH_REGISTER_COLLECT_ANIM, //105 ==== 模拟触发旅店收银台收获动画
        SIMULATE_CLICK_HERO_TEN_UPGRADE_TOGGLE, //106 ==== 模拟点击伙伴十连升级开关
        SIMULATE_CLICK_CHILD_ONE_KEY_TRAIN_TOGGLE, //107 ==== 模拟点击子嗣一键教学开关
        SIMULATE_CLICK_OPEN_CHILD_ONE_KEY_PLUS_WND, //108 ==== 模拟点击打开子嗣进阶一键教学窗口
        SIMULATE_CLICK_CHILD_ONE_KEY_TRAIN_PLUS_TOGGLE, //109 ==== 模拟点击子嗣进阶一键教学开关
        SIMULATE_CLICK_CONSORT_ONE_KEY_INVITE_TOGGLE, //110 ==== 模拟点击情人一键邀约开关
        SIMULATE_CLICK_OPEN_ARENA_ONE_KEY_BATTLE_SETTING, //111 ==== 模拟点击打开竞技场一键战斗设置窗口
        SIMULATE_CLICK_TRAVEL_ONE_KEY_TOGGLE, //112 ==== 模拟点击一键游历开关
        SIMULATE_CLICK_CHAPTER_QUICK_FORWARD_TOGGLE, //113 ==== 模拟点击关卡快速前进开关
        SIMULATE_CLICK_OPEN_CHAPTER_AUTO_SETTING, //114 ==== 模拟点击关卡自动设置界面
        SHOW_AIHELP, //115 ==== 打开AIHelp界面
        SIMULATE_CLICK_TREASURE_HUNT_MAIN_GAIN_ENERGY, //116 ==== 模拟点击领取太空打捞体力
        SIMULATE_CLICK_TREASURE_HUNT_MAIN_PLAY, //117 ==== 模拟点击前往太空打捞界面
        SIMULATE_CLICK_TREASURE_HUNT_GAME_PLAY, //118 ==== 模拟点击开始探索
        SIMULATE_CLICK_MIDDAY_DUNGEON_ENTER, //119 ==== 模拟点击太空维护按钮打开维护界面
        SIMULATE_CLICK_MIDDAY_DUNGEON_BATTLE_ATTACK, //120 ==== 模拟点击太空站维护派遣按钮
        SIMULATE_CLICK_EVENING_DUNGEON_ENTER, //121 ==== 模拟点击晚间副本(抵御陨石)按钮
        SIMULATE_CLICK_EVENING_DUNGEON_GAME_FIGHT, //122 ==== 模拟点击晚间副本派遣按钮
        SIMULATE_CLICK_TREASURE_HUNT_GAME_CHANGE_AREA, //123 ==== 模拟点击太空寻宝更换地点按钮
        SIMULATE_CLICK_TREASURE_HUNT_SELECT_AREA_GO, //124 ==== 模拟点击太空寻宝"前往"新区域
        SIMULATE_CLICK_CHAPTER_QUICK_FORWARD_SKIP_DIALOG_CONFIRM, //125 ==== 模拟点击关卡快速前进是否跳过对话"确认"按钮
        SIMULATE_CLICK_MARS_BUILDING_BUILD, //126 ==== 模拟点击火星建筑建造按钮
        SIMULATE_CLICK_SYSTEM_QUEST_BAR_REWARD, //127 ==== 模拟点击系统任务栏领取奖励按钮
        SIMULATE_CLICK_MARS_BUILDING_UPGRADE, //128 ==== 模拟点击火星建筑升级按钮
        SIMULATE_CLICK_MARS_RESIDENT_REPLENISH_FOLLOWER, //129 ==== 模拟点击火星居民补充按钮
        SIMULATE_CLICK_MARS_RESIDENT_REPLENISH, //130 ==== 模拟点击火星居民补充窗口补充按钮
        SIMULATE_CLICK_MARS_RESIDENT_REPLENISH_RESULT_SURE, //131 ==== 模拟点击火星居民补充结果确认按钮
        SIMULATE_CLICK_MARS_BUILDING_EQUIPMENT_UPGRADE, //132 ==== 模拟点击火星建筑装备升级按钮
        SIMULATE_CLICK_MARS_BUILDING_UPGRADE_WND_BTN, //133 ==== 模拟点击火星建筑升级按钮（建筑详情窗口）
        SIMULATE_CLICK_MARS_BUILDING_SETTLE, //134 ==== 模拟点击火星建筑结算按钮
        SIMULATE_CLICK_MARS_BUILDING_TECHNOLOGY_RESEARCH, //135 ==== 模拟点击火星建筑科技树研究按钮
        SIMULATE_CLICK_MARS_TECHNOLOGY_DETAIL_UPGRADE, //136 ==== 模拟点击火星科技详情升级按钮
        SIMULATE_CLICK_EXPLORE_TEAM_NORMAL_MARS_BUILDING, //137 ==== 模拟点击火星探索队伍建筑
        SIMULATE_CLICK_MARS_BUILDING_TEAM_EXPLORE_REPAIR, //138 ==== 模拟点击火星建筑队伍探索维修按钮
        SIMULATE_CLICK_MARS_EXPLORE_TEAM_HERO_EDIT_CONFIRM, //139 ==== 模拟点击火星探索队伍英雄编辑确认按钮
        SIMULATE_CLICK_MARS_EXPLORE_BATTLE_GO_EXPLORE, //140 ==== 模拟点击火星探索战斗前往探索按钮
        SIMULATE_CLICK_MARS_GO_TO_START_CONFIRM, //141 ==== 模拟点击前往火星确认按钮
        SIMULATE_CLICK_TOWER_RESEARCH, //142 ==== 模拟点击爬塔研究按钮
        SIMULATE_CLICK_MARS_LANDING_CONFIRM, //143 ==== 模拟点击火星着陆确认按钮
        MARS_HOME_COLLECT, //144 ==== 火星家园收取资源
        SET_SELECT_FIRST_NAMED_NO_GRADUATE_CHILD, //145 ==== 选择第一个已命名未毕业的子嗣
        SIMULATE_CLICK_MARS_BUILDING_HOME_INFO_SWITCH_ON_TOGGLE, //146 ==== 模拟点击火星家园建筑信息窗口开关按钮
        SIMULATE_CLICK_MARS_HOME_COLLECT, //147 ==== 模拟点击火星家园收集按钮
        SIMULATE_CLICK_BATCH_BUY_CONFIRM, //148 ==== 模拟点击批量购买确认
        SET_ARENA_CELEBRITY_ONE_BOT, //149 ==== 设置竞技场名人榜只有一个机器人
        SIMULATE_CLICK_MAIN_QUEST_GO_TO, //150 ==== 模拟点击主线任务前往按钮
        GUILD_COOPERATE_RESET_DEFAULT_AREA_SHOW, //151 ==== 联盟协作重置默认区域显示
        SIMULATE_CLICK_GUILD_COOPERATE_CAN_GET_REWARD_POS, //152 ==== 模拟点击联盟协作可领取奖励据点
        SIMULATE_CLICK_GUILD_COOPERATE_REWARD_POS_GET_REWARD, //153 ==== 模拟点击联盟协作可领取奖励据点领取奖励
        SIMULATE_CLICK_GUILD_COOPERATE_CAN_CONSTRUCT_ATTR_POS, //154 ==== 模拟点击联盟协作可建造属性据点
        SIMULATE_CLICK_GUILD_COOPERATE_DISPATCH_HERO, //155 ==== 模拟点击联盟协作派遣顾问
        SIMULATE_CLICK_INN_SPECIAL_GUEST_SERVE_BUTTON, //156 ==== 模拟点击旅店特殊客人接待按钮
    }
}

